### ISSUE TITLE
Feedback after reading through your documentation

### ISSUE THREAD

**Issue by dlk3** [Opire/docs#19]
What happens if the person who offers the reward turns out to be a deadbeat and refuses to pay?

Stripe charges different fees for different types of transactions.  How are your payments made?  As credit card payments?  As ACH transfers?  Something else?

How can I know that you'll be around for the long term?  I need to have confidence before I spend the time and effort necessary to train my project's community to use your services.  If you all were to disappear in six months or a year I would have wasted a lot of precious time.

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #19</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @dlk3</code> (replace <code>20</code> with the amount, and <code>@dlk3</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by RubenRuCh** [comment]
> What happens if the person who offers the reward turns out to be a deadbeat and refuses to pay?

We have a [FAQ](https://docs.opire.dev/faq) in our docs with a similar question ("What if I don't get paid")

But basically, it's a matter of trust in the community. We have our ways to detect unethical behaviour (systematically creating rewards without paying them), in which case we'll block the capability for creating new ones until they start paying the devs.

However, we haven't detected such behaviour yet. If in the future it starts to become a problem and our current mechanisms are not enough, we'll investigate further actions.

> Stripe charges different fees for different types of transactions. How are your payments made? As credit card payments? As ACH transfers? Something else?

We use Stripe Checkout to offer a secure payment gateway to the rewards creators. Stripe automatically offers different payment methods based on variables like IP, country, etc. That way, creators can pay with any payment method they prefer (as long as it's offered by Stripe in their checkout session). At the moment, most payments are being done by card.

We pay developers by making a direct transfer to their Stripe account, using the payment of the creator as the source for the transaction. We only receive our fee, and the Stripe fee that the creator paid (and will be deducted by Stripe directly in our account).

It's a system we had to setup with a lot of different variables in mind; the goal being that the developer always receive the 100% of the reward. The rest is taken care by Opire & the reward creator.

> How can I know that you'll be around for the long term? I need to have confidence before I spend the time and effort necessary to train my project's community to use your services. If you all were to disappear in six months or a year I would have wasted a lot of precious time.

Fair question. Obviously we don't plan to disappear, but I would also need some confidence / proof if I were in your place.

One of the key aspects of Opire is that we don't hold money. Creating a reward is done without any money coming out of the user's pocket. The only moment they have to pay, is when the developer has solved the issue and they are claiming the reward. And the transfer to the developer's Stripe account is done instantaneously once the reward creator has made the payment.

So that's already a difference VS other alternatives like Bountysource, that unfortunately disappeared some years ago and caused that a lot of people lost their money. If Opire disappeared, nobody loses their money.

Another thing: we have in our roadmap to completely being open-source. Since we're trying to make an impact in the open-source ecosystem, it make sense for us to have all our code accessible for everybody.

Before completely going open-source, we wanted to clean-up the house, release a few more functionalities that people have been asking for, agree in a set of rules for collaborations, etc. But we can prioritise it if it would make you more confident in Opire.

We're not going anywhere anytime soon. And if we do, the code will be accesible for anyone - the only thing you would need to do is self host the different services

---

Hope I could offer some clarity. If you want to know anything else, let us know!

**Comment by nabby27** [comment]
> How can I know that you'll be around for the long term?

On this point I would like to add one thing. I fully understand the concern, especially as it's a platform with little track record. The reality is that our costs are very low and even if we did not make money with this project we could afford to keep the servers active and continue offering our services. So I can assure you that we will not disappear.

**Comment by dlk3** [comment]
Thanks
